### ISSUE TITLE
Multilingual docs article

### ISSUE THREAD

**Issue by cpw10** [CloudCannon/platform-documentation#76] opened 2023-05-17 15:23 UTC
We frequently get questions about how to set up multilingual sites in CloudCannon. Creating an article can alleviate a lot of back and forth for both sales and support.

**Comment by rphillips-cc** [comment] 2023-06-07 01:19
duplicate of https://github.com/CloudCannon/platform-documentation/issues/43

**Closed by rphillips-cc** 2023-06-07 01:19 UTC
