### ISSUE TITLE
Incomplete HTML and markdown input docs

### ISSUE THREAD

**Issue by tomrcc** [CloudCannon/platform-documentation#44] opened 2023-04-26 21:23 UTC
[This ](https://cloudcannon.com/documentation/articles/using-rich-text-inputs-to-edit-your-data/#valid-values) last part of this page looks incomplete. No valid values, related articles or related links are listed, resulting in some empty headings at the end of the page.

**Comment by rphillips-cc** [comment] 2023-06-09 00:50
Duplicate of https://github.com/CloudCannon/platform-documentation/issues/29

**Closed by rphillips-cc** 2023-06-09 00:50 UTC
